/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoginCf;

import Dao.LoginDao;
import Helper.DangNhap;
import Model.LoginModel;
import Windows.admin;
import Windows.nhanvien;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
//import java.util.regex.Matcher;
//import java.util.regex.Pattern;
/**
 *
 * @author DIEM QUYNH
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userName = new javax.swing.JLabel();
        NhapUsername = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        NhapPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1070, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userName.setForeground(new java.awt.Color(255, 255, 51));
        userName.setText("User");
        getContentPane().add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 69, -1));

        NhapUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhapUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(NhapUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 137, -1));

        Password.setForeground(new java.awt.Color(255, 255, 51));
        Password.setText("Password");
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 69, -1));

        NhapPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhapPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(NhapPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 137, -1));

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 150, 30));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/backgrond_hoa_huong_duong.jpg"))); // NOI18N
        jLabel1.setText("z");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 600));

        setBounds(0, 0, 1084, 607);
    }// </editor-fold>//GEN-END:initComponents

    private void NhapUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhapUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NhapUsernameActionPerformed

    private void NhapPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhapPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NhapPasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    try {
            String name = NhapUsername.getText();
            String password = new String(NhapPassword.getPassword());
            Pattern pattern = Pattern.compile("[a-zA-Z0-9_-]{3,10}$");
            Matcher matcher = pattern.matcher(name);
            Matcher matcher1 = pattern.matcher(password);
            if (matcher.find() && matcher1.find()) {
                LoginDao dao = new LoginDao();
                LoginModel tk = dao.checkLogin(name, password);
                if (tk == null) {
                    JOptionPane.showMessageDialog(null, "Username or password is incorrect");
                } else {
                    JOptionPane.showMessageDialog(null, "Login thành công");
                    DangNhap.Username = name;
                    DangNhap.Password = password;
                    dispose(); //Phá hủy cửa sổ login khi đăng nhập xong
                    //Chổ để code khi đã Login thành công
                    if (dao.findByKiemtra(name, "admin") != null) {
                        admin apage = new admin();
                        apage.setVisible(true);
                    } else if (dao.findByKiemtra(name, "user") != null) {
                        nhanvien upage = new nhanvien();
                        upage.setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(null, "Error login");
                    }
                }
            } else {
                   JOptionPane.showMessageDialog(null,"Please enter the correct information");
                   }
        } catch (Exception el) {
            el.printStackTrace();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        NhapUsername.setText("");
        NhapPassword.setText("");
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField NhapPassword;
    private javax.swing.JTextField NhapUsername;
    private javax.swing.JLabel Password;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
