/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Windows;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
/**
 *
 * @author DIEM QUYNH
 */
public class DrinkMenu extends javax.swing.JFrame {
    private JPanel contentPane;
    private JPanel panel;
    private JLabel lblImage;
    private JLabel lblName;
    private JLabel lblPrice;
    private JSpinner spinner;
    private List<Drink> drinks;
    
    /**
     * Creates new form DrinkMenu
     */
    public DrinkMenu() {
//        setTitle("GridLayout Example");
//        setSize(500, 500);
//        
//        //dữ liệu giả
//        drinks = new ArrayList<Drink>();
//        drinks.add(new Drink("Coffee", "2000", "/Image/cafeda.jpg"));
//        drinks.add(new Drink("Milk Tea", "2000", "/Image/cafeda.jpg"));
//        drinks.add(new Drink("Fruit Smoothie", "2000", "/Image/cafeda.jpg"));
//        drinks.add(new Drink("Fruit Smoothie", "2000", "/Image/cafeda.jpg"));
//        drinks.add(new Drink("Fruit Smoothie", "2000", "/Image/cafeda.jpg"));
//          drinks.add(new Drink("Fruit Smoothie", "2000", "/Image/cafeda.jpg"));
//            drinks.add(new Drink("Fruit Smoothie", "2000", "/Image/cafeda.jpg"));
//        
//        contentPane = new JPanel();
//        contentPane.setLayout(new GridLayout(0, 3, 10, 10));
//       
//
//        
//        
//        // Add the drinks to the table
//        for (Drink drink : drinks) {
//            JLabel nameLbl = new JLabel(drink.getName());
//             JLabel priceLbl = new JLabel(drink.getPrice());
//            ImageIcon image = new ImageIcon(getClass().getResource(drink.getImageUrl()));
//            JLabel imageLbl = new JLabel(image);
//            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 100, 1);
//            spinner = new JSpinner(model);
//            contentPane.add(nameLbl);
//            contentPane.add(priceLbl);
//            contentPane.add(imageLbl);
//            contentPane.add(spinner);  
//        }
//
////        panel = new JPanel();
////        panel.setLayout(new GridLayout(0, 4, 10, 10)); // 0 rows, 4 columns, 10px horizontal gap, 10px vertical gap
////
////        for (int i = 1; i <= 10; i++) { // Add 10 buttons to the panel
////            JButton button = new JButton("Button " + i);
////            panel.add(button);
////        }
//        add(contentPane, BorderLayout.CENTER);
      // Tạo panel chứa sản phẩm với GridLayout 5 cột
      JPanel productPanel = new JPanel(new GridLayout(0, 5));
      
      // Thêm các sản phẩm vào panel
      for (int i = 1; i <= 100; i++) {
         // Tạo panel sản phẩm
         JPanel product = new JPanel(new BorderLayout());
         
         // Thêm hình ảnh sản phẩm vào panel
         ImageIcon image = new ImageIcon("product" + i + ".jpg");
         JLabel imageLabel = new JLabel(image);
         product.add(imageLabel, BorderLayout.CENTER);
         
         // Thêm tên sản phẩm vào panel
         JLabel nameLabel = new JLabel("Sản phẩm " + i);
         product.add(nameLabel, BorderLayout.NORTH);
         
         // Thêm giá sản phẩm vào panel
         JLabel priceLabel = new JLabel("$10.00");
         product.add(priceLabel, BorderLayout.SOUTH);
         
         // Thêm panel sản phẩm vào panel chứa sản phẩm
         productPanel.add(product);
      }
      
      // Tạo JScrollPane để cuộn nếu cần
      JScrollPane scrollPane = new JScrollPane(productPanel);
      
      // Thêm JScrollPane vào JFrame
      add(scrollPane);
      
      // Thiết lập kích thước JFrame và hiển thị nó
      setSize(800, 600);
    }
    
    private class Drink {
        private String name;
        private String price;
        private String imageUrl;

        public Drink(String name, String price, String imageUrl) {
            this.name = name;
            this.price = price;
            this.imageUrl = imageUrl;
        }

        public String getName() {
            return name;
        }

        public String getPrice() {
            return price;
        }

        public String getImageUrl() {
            return imageUrl;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("In hóa đơn");

        jButton2.setText("Tổng tiền");

        jButton3.setText("Làm mới");

        jButton4.setText("Thoát");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(62, 62, 62)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(53, 53, 53)
                .addComponent(jButton4)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrinkMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrinkMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrinkMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrinkMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrinkMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
